### ISSUE TITLE
How to browserify ts-npm module

### ISSUE THREAD

**Issue by shadeglare** [basarat/ts-npm-module-consume#1]
I'm using `browserify` with `tsify` extension to bundle frontend js but can't get it to work properly. For some reasons ts npm module can not be found but it works find when using built-in atom typescript compilation on save.

The code snippet:

``` javascript
var browserify = require("browserify");
var tsify = require("tsify");
var fs = require("fs");

browserify()
    .add('main.ts')
    .plugin('tsify', { noImplicitAny: true })
    .bundle()
    .on('error', function (error) { console.error(error.toString()); })
    .pipe(fs.createWriteStream("bundle.js"));
```

where main.ts is a typescript file that imports a ts node module.

**Comment by basarat** [comment]
> ts npm module can not be found but it works find when using built-in atom typescript

Probably need to use typescript nightly (or ntypescript https://github.com/TypeStrong/ntypescript)
