### ISSUE TITLE
how to create module for future import like import {blabla} from "oops/bla/ups"?

### ISSUE THREAD

**Issue by stepancar** [basarat/ts-npm-module-consume#3]
Hello @basarat;
in react-router used import 

``` javascript
import createBrowserHistory from 'history/lib/createBrowserHistory'
```

i want create npm typescript module, which i will import with path like this;
i know, that d.ts looks like this 

``` javascript
/// just declare module with this name
declare module "history/lib/createBrowserHistory" {
    export default function createBrowserHistory(): HistoryModule.History
}
```

But how to create module with 'history/lib/createBrowserHistory' name using typescript?
Thank you!

**Comment by basarat** [comment]
> 'history/lib/createBrowserHistory' name using typescript?

There needs to be a `createBrowserHistory.d.ts` file at the location `node_modules/history/lib`
