### ISSUE TITLE
How to consume the module in the browser?

### ISSUE THREAD

**Issue by pablodenadai** [basarat/ts-npm-module-consume#4]
Can your module be consumed via a web browser?
#### Setup

**app.ts**

``` js
import * as SampleModule from 'ts-npm-module';
```

**index.html**

``` html
<script src="../node_modules/ts-npm-module/js/index.js"></script>
```
#### Error

`Uncaught ReferenceError: require is not defined - index.js:4`

**Comment by basarat** [comment]
> Can your module be consumed via a web browser?

Use webpack (recommended) or browserify.

For a sample checkout https://github.com/TypeScriptBuilder/tsb/ that uses various packages like this e.g. csx : https://github.com/TypeScriptBuilder/tsb/blob/e34748fc7ccdb8286a7b6ee7bced9b67a969f037/package.json#L57 :rose:
